service: backend-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  getAgendas:
    handler: src/agenda/controller/getAgendas.handler
    events:
      - http:
          path: agendas
          method: get
          cors: true
  createAgendamento:
    handler: src/agendamento/controller/createAgendamento.handler
    events:
      - http:
          path: agendamento
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .gitignore
    - README.md
